### ISSUE TITLE
1.1 - User Input - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#1]
This program should prompt for and accept

-someone's name
-someone's ideal legal situation (from the following options)
1. "I am law abiding!"
2. "I make sure others obey the law."
3. "I live outside the law."
4. "Questionable."

and return one of these based on legal situation: 
1. The Empire thanks you for your aquiescence, citizen **name**. 
2. **name**, aren't you a little short for a Storm Trooper? 
3. Hey, **name**! Who's scruffy-lookin'? 
4. **name**, I loathe bounty hunters. We don't need their scum... 
   If selection is invalid, return:
   **name**, meesa Jar Jar Binks.

Tasks
### Tasks
- [x] Create a new Issue with these tasks! (S)
- [x] Use the Github web interface to create a repository called `1.1-User-Input`
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [x] In Github, open a PR from `<initials>-develop` into `master`
- [x] Create the Quick Star Wars Character test (L)
  - [x] Checkpoint: Create `assignment.rb` 
  - [x] Checkpoint: Store a person's name from a prompt
  - [x] Checkpoint: Store a person's legal preference
  - [x] Checkpoint: Perform logic on the legal preference
  - [x] Checkpoint: Return one of the required strings back to the user.
  - [x] Checkpoint: Commit `assignment.rb`
  - [x] Complete: Pushed `assignment.rb`

Solution: https://github.com/andrewtpoe/1.1-User-Input/pull/1

**Comment by andrewtpoe** [comment]
Tasks

### Tasks
- [ ] Create a new Issue with these tasks!
- [ ] Use the Github web interface to create a repository called `1.1-User-Input`
- [ ] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [ ] In Github, open a PR from `<initials>-develop` into `master`
- [ ] Create the Quick Star Wars Character test
  - [ ] Checkpoint: Create `assignment.rb`
  - [ ] Checkpoint: Store a person's name from a prompt
  - [ ] Checkpoint: Store a person's legal preference
  - [ ] Checkpoint: Perform logic on the legal preference
  - [ ] Checkpoint: Return one of the required strings back to the user.
  - [ ] Checkpoint: Commit `assignment.rb`
  - [ ] Complete: Pushed `assignment.rb`
