### ISSUE TITLE
1.1 - User Input -- Ryan McGovern

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#10]
Repo link: https://github.com/ryanmcgov/1.1-User-Input
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.1-User-Input`
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [x] In Github, open a PR from `<initials>-develop` into `master`
- [x] Create the Quick Star Wars Character test
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Store a person's name from a prompt
  - [x] Checkpoint: Store a person's legal preference
  - [x] Checkpoint: Perform logic on the legal preference
  - [x] Checkpoint: Return one of the required strings back to the user.
  - [x] Checkpoint: Commit `assignment.rb`
  - [x] Complete: Pushed `assignment.rb`

**Comment by rpearce** [comment]
@ryanmcgov Next time, please leave the Pull Request open so that we can iterate the code that's in there.

**Comment by rpearce** [comment]
I'm going to comment on the closed one(s) in the mean time, so lookout for comments there
