### ISSUE TITLE
4.1 - Sinatra -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#103]
**PR:** https://github.com/easmith2/4.1-Sinatra/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `4.1-Sinatra`
- [x] Create a branch on `4.1-Sinatra` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the Sinatra App
  - [x] Checkpoint: Create a `Gemfile`, `app.rb`, and your `views/` directory
  - [x] Checkpoint: Set the Gemfile to install `sinatra`
  - [x] Checkpoint: Set up your `app.rb` to route to at least `'/'`, `'/my-post'`, and `'/my-other-post'`
  - [x] Checkpoint: Create a layout file
  - [x] Checkpoint: Create a separate, new index page (located at `'/'`) that links to at least 2 different surf & paddle pages
  - [x] Checkpoint: Create an index file and a post file(s) and any other necessary partials
  - [x] Checkpoint: Make sure each page has the appropriate `<title>`
  - [ ] Checkpoint: HARD MODE: Use the same template/partial for both blog posts
  - [x] Complete: pushed all relevant code
