### ISSUE TITLE
4.2 - Rails First Step - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#107]
![](http://media.giphy.com/media/tevIMK66n6Ju8/giphy.gif)
### Solution

Link: https://github.com/andrewtpoe/4.2-Rails-First-Step/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `4.2 - Rails-First-Step -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `4.2-Rails-First-Step` containing at least a `README.md` file
- A Pull Request (PR) in your `4.2-Rails-First-Step` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements
- Make all the things work.
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `4.2-Rails-First-Step`
- [x] Create a branch on `4.2-Rails-First-Step` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the website
  - [x] Checkpoint: created Rails app
  - [x] Checkpoint: create default `root` route
  - [x] Checkpoint: create some sort of home/non-resource-specific controller
  - [x] Checkpoint: implemented static HTML views
  - [x] Checkpoint: implemented dynamic views (variables, template partial rendering)
  - [x] Checkpoint: added Sass
  - [x] Checkpoint: made it all work how a website should work
  - [x] Complete: pushed all relevant code
