### ISSUE TITLE
1.2 - Countries -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#11]
### Tasks
- [x] Create a new Issue with these tasks! (s)
- [x] Use the Github web interface to create a repository called `1.2-Countries` (s)
- [x] Use the Github web interface to create a branch on `1.2-Countries` called `dev` (s)
- [x] In Github, open a PR from `<initials>-develop` into `master` (s)
- [x] Write a Ruby program that manipulates the given countries.txt file: (m)
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: reads the file
  - [x] Checkpoint: determine how many countries there are listed in the file
  - [x] Checkpoint: capitalize each word in a country's name that is not `and`, `of`, or `the`
  - [x] Checkpoint: Replaces the `|` with `-`.
  - [x] Checkpoint: Write the newly formatted countries to a new file named `updated_countries.txt`
  - [x] Complete: Pushed `assignment.rb`

**PR:** https://github.com/easmith2/1.2-countries/pull/1
