### ISSUE TITLE
4.2-Rails-First-Steps-Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#111]
PR: https://github.com/mcmillanator/4.2-Rails-First-Steps/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `4.2-Rails-First-Step`
- [x] Create a branch on `4.2-Rails-First-Step` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the website
  - [x] Checkpoint: created Rails app
  - [x] Checkpoint: create default `root` route
  - [x] Checkpoint: create some sort of home/non-resource-specific controller
  - [x] Checkpoint: implemented static HTML views
  - [x] Checkpoint: implemented dynamic views (variables, template partial rendering)
  - [x] Checkpoint: added Sass
  - [x] Checkpoint: made it all work how a website should work
  - [x] Complete: pushed all relevant code

**Comment by rpearce** [comment]
is this still `wip`?
