### ISSUE TITLE
4.3 - Albums - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#112]
![](http://media.giphy.com/media/Jv0Kbxn0qhKko/giphy.gif)
### Solution

Link: https://github.com/andrewtpoe/4.3-Albums/pull/1
### Tasks
- [x] Create new postgresql rails project called albums
- [x] Generate an album model/ table/ tests (title, genre, artist, length(minutes))
- [x] Add model validations to ensure no fields are blank
- [x] Add validation for length to be greater than 0
- [x] Add validation for title & artist to not have duplicates
- [x] Ensure calling .save actually saves to db.
- [x] Write tests for these conditions
