### ISSUE TITLE
4.3 - Albums -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#113]
**PR:** https://github.com/easmith2/albums/pull/1
### Tasks
- [x] Create new postgresql rails project called albums
  - [x] Generate an album model/table/tests (with title, genre, artist, length (in minutes))
  - [x] Add model validations to ensure no fields are null
  - [x] Add validation for length to be > 0
  - [x] Add validation for title and artist to not have duplicates (not that artist can only appear once, but that artist+title combination only appears once)
  - [x] Write tests for these conditions
    - [x] test both positive and negative (i.e. test that something is valid and something else is not)
  - [x] Ensure calling `.save` actually saves to the db
