### ISSUE TITLE
4.3 - Albums -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#115]
![](http://media.giphy.com/media/1j4cUACW5YB7a/giphy.gif)

https://github.com/ryanmcgov/4.3-Albums/pull/1
### Tasks
- [x] Create new postgresql rails project called albums
- [x] Generate an album model/ table/ tests (title, genre, artist, length(minutes))
- [x] Add model validations to ensure no fields are blank
- [x] Add validation for length to be greater than 0
- [x] Add validation for title & artist to not have duplicates
- [x] Ensure calling .save actually saves to db.
- [x] Write tests for these conditions
