### ISSUE TITLE
4.3-albums-seanpage

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#116]
https://github.com/seanmpage/albums_4.3/pull/1
### Tasks
- [x] Create new postgresql rails project called albums
  - [x] Generate an album model/table/tests (with title, genre, artist, length (in minutes))
  - [x] Add model validations to ensure no fields are null
  - [x] Add validation for length to be > 0
  - [x] Add validation for title and artist to not have duplicates (not that artist can only appear once, but that artist+title combination only appears once)
  - [x] Write tests for these conditions
    - [x] test both positive and negative (i.e. test that something is valid and something else is not)
  - [x] Ensure calling `.save` actually saves to the db

**Comment by rpearce** [comment]
is this still a `wip`?
