### ISSUE TITLE
4.3 - Rails-Model -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#118]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Rails-Model-4.3` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create data model/specs
  - [x] Checkpoint: Created new `postgresql` Rails project
  - [x] Checkpoint: Generated an `Album` model with `title:string`, `artist:string`, `genre:string`, `length:integer`
  - [x] Checkpoint: Added validations to ensure no fields are blank
  - [x] Checkpoint: Added validation to ensure length > 0
  - [x] Checkpoint: Added validation for `title` & `artist` to not have duplicates
  - [ ] Checkpoint: Ensured calling `album.save` actually saves to the database
  - [x] Checkpoint: Wrote tests for these validations
  - [x] Complete: pushed all relevant code

[Pull Request](https://github.com/Kennethjk3/albums/pull/1)
![](https://usatftw.files.wordpress.com/2013/10/dino.gif?w=1000)
