### ISSUE TITLE
4.4 - CRUDdy Music Manager - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#119]
![](http://cdn1.theodysseyonline.com/files/2015/07/06/635717508385550496-957215644_enddd.gif)
### Solution

Link: https://github.com/andrewtpoe/4.4-CRUD/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `WEEK.DAY - TITLE -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `WEEK.DAY-TITLE` containing at least a `README.md` file
- A Pull Request (PR) in your `WEEK.DAY-TITLE` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements
- the root route should work (this can be the albums' index page)
- an `Album` model (with specs)
- an `AlbumsController` which encompasses all of the CRUD actions
- the appropriate routes in the routes folder
- `index` `new` and `edit` pages
- a form on the `/albums/new` page
- a form on the `/albums/edit` page
- error message handling for each form
- the controller should handle what happens in any use case
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `TITLE-WEEK.DAY` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create a CRUD app!
  - [x] Checkpoint: created the `Album` model
  - [x] Checkpoint: created the `AlbumsController`
  - [x] Checkpoint: set the `config/routes.rb` file up
  - [x] Checkpoint: created all the other actions & pages
  - [x] Checkpoint: made sure all pages redirect/re-render like they should
  - [x] Checkpoint: handled all form errors
  - [ ] HARD MODE: created tests around every action and scenario for your controller
  - [x] Complete: pushed all relevant code
