### ISSUE TITLE
4.4 - CRUD -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#122]
https://github.com/ryanmcgov/4.4-CRUD/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `TITLE-WEEK.DAY` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create a CRUD app!
  - [x] Checkpoint: created the `Album` model
  - [x] Checkpoint: created the `AlbumsController`
  - [x] Checkpoint: set the `config/routes.rb` file up
  - [x] Checkpoint: created all the other actions & pages
  - [x] Checkpoint: made sure all pages redirect/re-render like they should
  - [x] Checkpoint: handled all form errors
  - [ ] HARD MODE: created tests around every action and scenario for your controller
  - [x] Complete: pushed all relevant code
