### ISSUE TITLE
4.4 - CRUD -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#123]
**PR:** https://github.com/easmith2/4.4-CRUD/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `TITLE-WEEK.DAY` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create a CRUD app!
  - [x] Checkpoint: created the `Album` model
  - [x] Checkpoint: created the `AlbumsController`
  - [x] Checkpoint: set the `config/routes.rb` file up
  - [x] Checkpoint: created all the other actions & pages
  - [x] Checkpoint: made sure all pages redirect/re-render like they should
  - [x] Checkpoint: handled all form errors
  - [x] HARD MODE: created tests around every action and scenario for your controller (I only made tests for some actions, but will likely go back and add more.)
  - [x] Complete: pushed all relevant code
### Requirements
- the root route should work (this can be the albums' index page)
- an `Album` model (with specs)
- an `AlbumsController` which encompasses all of the CRUD actions
- the appropriate routes in the routes folder
- `index` `new` and `edit` pages
- a form on the `/albums/new` page
- a form on the `/albums/edit` page
- error message handling for each form
- the controller should handle what happens in any use case
