### ISSUE TITLE
4.4 - CRUD -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#125]
[Pull Request](https://github.com/Kennethjk3/CRUD_Practice/pull/1)-This is one I did to practice CRUDing...it makes bookmarks to websites

![](http://static1.squarespace.com/static/5193c946e4b0566afb22a10e/551dfc35e4b0a24bf6be3b2c/551dfc36e4b09619c3abf735/1428028473427/coffee_time_futurama.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `CRUD-4.4` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create a CRUD app!
  - [x] Checkpoint: created the `Album` model
  - [x] Checkpoint: created the `AlbumsController`
  - [x] Checkpoint: set the `config/routes.rb` file up
  - [x] Checkpoint: created all the other actions & pages
  - [x] Checkpoint: made sure all pages redirect/re-render like they should
  - [x] Checkpoint: handled all form errors
  - [ ] HARD MODE: created tests around every action and scenario for your controller
  - [x] Complete: pushed all relevant code

[Assignment's Pull Request](https://github.com/Kennethjk3/4.4-CRUD/pull/1)

**Comment by Kennethjk3** [comment]
can't find where artist is made into a link
