### ISSUE TITLE
5.1 - Moosic -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#126]
**PR:** https://github.com/easmith2/5.1-Moosic/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Model all the things!
  - [x] Checkpoint: Sketched out models & their associations
  - [x] Checkpoint: Created Rails models for each class
  - [x] Checkpoint: Set up relationships for models
  - [ ] Checkpoint: Test relationships
  - [ ] HARD MODE: Create a web interface to manage all this
  - [ ] Complete: pushed all relevant code
