### ISSUE TITLE
5.1 - MoosicApp -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#127]
![](http://25.media.tumblr.com/tumblr_mejkhmNfyf1roxoq5o1_500.gif) 
[Pull Request](https://github.com/Kennethjk3/5.1-MoosicManager/pull/1)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Moosic-5.1` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Model all the things!
  - [ ] Include:
    - [ ] Album M(VC)
    - [ ] Song M(VC)
    - [ ] Artist M(VC)
    - [ ] Genre M(VC)
    - [ ] Playlist M(VC)
  - [ ] Checkpoint: Sketched out models & their associations
  - [ ] Checkpoint: Created Rails models for each class
  - [ ] Checkpoint: Set up relationships for models
  - [ ] Checkpoint: Test relationships
  - [ ] HARD MODE: Create a web interface to manage all this
  - [ ] Complete: pushed all relevant code
