### ISSUE TITLE
1.2 - Countries - Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#13]
https://github.com/jasimper/1.2-Countries/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.2-Countries`
- [x] Use the Github web interface to create a branch on `1.2-Countries` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write a program that reads the countries file and returns the number of countries, as well as the syntactic updates mentioned above.
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Load in the `countries.txt` file
  - [x] Checkpoint: Programmatically determine how many countries there are
  - [x] Checkpoint: Capitalize each word in a country's name that is not `and`, `of` or `the`
  - [x] Checkpoint: Replace the `|` symbol with `-` (or " - ")
  - [x] Checkpoint: Write the newly formatted countries to a new file named `updated_countries.txt`
  - [x] Complete: Pushed `assignment.rb`
