### ISSUE TITLE
5.1 - Moosic -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#130]
https://github.com/jasimper/5.1-Moosic/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Moosic-5.1` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Model all the things!
  - [x] Checkpoint: Sketched out models & their associations
  - [x] Checkpoint: Created Rails models for each class
  - [x] Checkpoint: Set up relationships for models
  - [x] Checkpoint: Test relationships
  - [ ] HARD MODE: Create a web interface to manage all this
  - [x] Complete: pushed all relevant code
