### ISSUE TITLE
5.1 - Moosic - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#131]
### What I have so far...

Link: https://github.com/andrewtpoe/5.1-moosic/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `5.1 - Moosic -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `5.1-Moosic` containing at least a `README.md` file
- A Pull Request (PR) in your `5.1-Moosic` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements
- Build model associations for a music management app. Here are some starter classes:
  - `Artist`
  - `Album`
  - `Playlist`
  - `Genre`
- These these associations & whatever else needs to be
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Moosic-5.1` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] Model all the things!
  - [x] Checkpoint: Sketched out models & their associations
  - [x] Checkpoint: Created Rails models for each class
  - [x] Checkpoint: Set up relationships for models
  - [ ] Checkpoint: Test relationships
  - [ ] HARD MODE: Create a web interface to manage all this
  - [x] Complete: pushed all relevant code
