### ISSUE TITLE
5.2 - Nested Resources - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#132]
### Link:

https://github.com/andrewtpoe/5.2-Nested-Resources/pull/1
### Deliverables
- An issue in the class repo
- A Pull Request in your repo with files that meet the requirements below
- A comment on your original issue with a link to your PR.
### Requirements
- Build model associations with at least the following classes:
  - `Artist`
  - `Album`
  - `Song`
- Create tests for models and controllers to guide the development of this project.
- Create basic CRUD functionality for all models.
### Tasks
- [x] Create a new issue with these tasks
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly created, unedited Rails project to your `master` branch on Github
- [x] Create a `dev` branch for this project
- [x] Open a Pull Request from `dev` into `master`
- [ ] Create project with minimum of these features:
  - [x] Valid models, associations, and tests for at least Artists, Albums, and Songs.
  - [x] Nested resources for artists, albums, and songs.
  - [ ] Display all albums and songs from artist on artist's index page.
  - [ ] User can add/ edit/ and delete albums (link on artist's index page).
  - [ ] User can add/ edit/ and delete songs in an album (link on artist's index page).
  - [ ] Validate all form submissions
  - [ ] Test all the things

**Comment by adam-kelsey** [comment]
super win.
