### ISSUE TITLE
5.2 - Nested-Resources -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#134]
https://github.com/ryanmcgov/5.2-Nested-Resources/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Nested-Resources-5.2` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] CRUD Moosic app
  - [x] Checkpoint: CRUD for an `Artist`
  - [ ] Checkpoint: CRUD for an `Artist`'s `Album`
  - [ ] Checkpoint: CRUD for an `Artist`'s `Album`'s `Song`
  - [ ] Complete: pushed all relevant code
