### ISSUE TITLE
5.2 - Nested-Resources -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#136]
https://github.com/jasimper/5.2-Nested-Resources/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Nested-Resources-5.2` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] CRUD Moosic app
  - [x] Checkpoint: CRUD for an `Artist`
  - [x] Checkpoint: CRUD for an `Artist`'s `Album`
  - [x] Checkpoint: CRUD for an `Artist`'s `Album`'s `Song`
  - [x] Complete: pushed all relevant code
