### ISSUE TITLE
5.2-Nested-Resources-Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#138]
### Tasks
- [x] Create a new Issue with these tasks!
- [ ] Create a Rails project & initialize it with git
- [ ] Commit the newly committed, unedited Rails project to your `master` branch
- [ ] Create a branch on `Nested-Resources-5.2` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] CRUD Moosic app
  - [ ] Checkpoint: CRUD for an `Artist`
  - [ ] Checkpoint: CRUD for an `Artist`'s `Album`
  - [ ] Checkpoint: CRUD for an `Artist`'s `Album`'s `Song`
  - [ ] Complete: pushed all relevant code
