### ISSUE TITLE
5.2 - Nested Resources -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#140]
![](https://38.media.tumblr.com/tumblr_m034lzXRDB1r70r3vo1_400.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [ ] Commit the newly committed, unedited Rails project to your `master` branch
- [ ] Create a branch on `Nested-Resources-5.2` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [x] CRUD Moosic app
  - [x] Checkpoint: CRUD for an `Artist`
  - [x] Checkpoint: CRUD for an `Artist`'s `Album`
  - [x] Checkpoint: CRUD for an `Artist`'s `Album`'s `Song`
  - [ ] Complete: pushed all relevant code
#### Requirements
- `Artist` CRUD
- `Album` CRUD for an individual `Artist`
- `Song` CRUD for an individual `Album`
##### Nested resources must be utilized for this assignment

[Pull Request](https://github.com/Kennethjk3/5.2-Nested-Resources/pull/1)
