### ISSUE TITLE
5.3 - JSON - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#144]
![](http://i.imgur.com/u6d7BLn.gif)
### Link

https://github.com/andrewtpoe/5.3-JSON/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `5.3 - Rails-JSON -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `5.3-Rails-JSON` containing at least a `README.md` file
- A Pull Request (PR) in your `5.3-Rails-JSON` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements
- 1 fully tested model
- 1 fully tested JSON controller with the following actions
  - `index`
  - `create`
  - `show`
  - `update`
  - `destroy`
- HARD MODE: have the controller actions respond to both HTML & JSON
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Rails-JSON-5.3` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create JSON app API
  - [x] Checkpoint: created and tested model
  - [x] Checkpoint: created and tested JSON controller
  - [ ] HARD MODE: allowed controller actions to respond to HTML as well as JSON
  - [x] Complete: pushed all relevant code
