### ISSUE TITLE
5.3 - Rails-JSON -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#146]
https://github.com/ryanmcgov/5.3-Rails-JSON/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Rails-JSON-5.3` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Create JSON app API
  - [ ] Checkpoint: created and tested model
  - [ ] Checkpoint: created and tested JSON controller
  - [ ] HARD MODE: allowed controller actions to respond to HTML as well as JSON
  - [ ] Complete: pushed all relevant code
