### ISSUE TITLE
5.3 - Rails-JSON --Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#149]
![](http://themadmonkeys.com/images/smilies/hugebanana.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Rails-JSON-5.3` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create JSON app API
  - [x] Checkpoint: created and tested model
  - [ ] Checkpoint: created and tested JSON controller
  - [ ] HARD MODE: allowed controller actions to respond to HTML as well as JSON
  - [x] Complete: pushed all relevant code
##### Requirements
- 1 fully tested model
- 1 fully tested JSON controller with the following actions
  - `index`
  - `create`
  - `show`
  - `update`
  - `destroy`
- HARD MODE: have the controller actions respond to both HTML & JSON

[Pull Request](https://github.com/Kennethjk3/5.3-JSON/pull/1)

**Comment by Kennethjk3** [comment]
@rpearce @adam-kelsey 
working on testing now
