### ISSUE TITLE
1.2 countries - Stanley

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#15]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.2-Countries`
- [x] Use the Github web interface to create a branch on `1.2-Countries` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write a program that reads the countries file and returns the number of countries, as well as the syntactic updates mentioned above.
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Load in the `countries.txt` file
  - [x] Checkpoint: Programmatically determine how many countries there are
  - [x] Checkpoint: Capitalize each word in a country's name that is not `and`, `of` or `the`
  - [x] Checkpoint: Replace the `|` symbol with `-` (or " - ")
  - [x] Checkpoint: Write the newly formatted countries to a new file named `updated_countries.txt`
  - [x] Complete: Pushed `assignment.rb`

PR: https://github.com/mcmillanator/1.2-countries

**Comment by mcmillanator** [comment]
I don't think I'm doing the PR correctly.  I might have it correct on 1.3, but not yet sure.  I should have it right by 1.4.  I'll do some testing elsewhere until I understand.  :)

**Comment by rpearce** [comment]
Haha nope! Talk to Andrew or Sean and/or check out their script

**Comment by rpearce** [comment]
Code looks :+1:. Nice popup.
