### ISSUE TITLE
5.3 - JSON - Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#150]
https://github.com/jasimper/5.3-JSON/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Rails-JSON-5.3` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create JSON app API
  - [x] Checkpoint: created and tested model
  - [x] Checkpoint: created and tested JSON controller
  - [ ] HARD MODE: allowed controller actions to respond to HTML as well as JSON
  - [x] Complete: pushed all relevant code
