### ISSUE TITLE
5.1-moosic-Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#152]
PR: https://github.com/mcmillanator/5.1-Moosie/pull/1
### Requirements
- Build model associations for a music management app. Here are some starter classes:
  - `Artist`
  - `Album`
  - `Playlist`
  - `Genre`
- These these associations & whatever else needs to be
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Moosic-5.1` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Model all the things!
  - [ ] Checkpoint: Sketched out models & their associations
  - [ ] Checkpoint: Created Rails models for each class
  - [ ] Checkpoint: Set up relationships for models
  - [ ] Checkpoint: Test relationships
  - [ ] HARD MODE: Create a web interface to manage all this
  - [ ] Complete: pushed all relevant code
