### ISSUE TITLE
6.1-6.2 - Grocery Data -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#153]
**6.1 & 6.2: PR:** https://github.com/easmith2/6.1-6.4-Grocery-Data/pull/1
### Tasks
- [x] Clone the provided Rails project, initialize your own repo
- [x] 6.1: Add user authentication
  - [x] Don't use Devise
  - [x] A user must be logged in to view the index page
  - [x] The index page should only show items for the current user
  - [x] Add necessary tests
- [x] 6.2: Pagination
  - [x] Paginate the items list
- [x] Open a PR for review

**Comment by easmith2** [comment]
6.1: I only added some of the tests, but I think the (basic) authentication is done.

**Comment by easmith2** [comment]
6.2: Added a couple more tests, still can't figure out how to test the method defined in the application controller. Pagination added for items list.

**Comment by mcmillanator** [comment]
See if you can move your method to a helper as a module.  Then include that module in the application controller.  Then you should be able to write a test for that helper.

http://guides.rubyonrails.org/testing.html  11 Testing Helpers

Hope that works.
