### ISSUE TITLE
6.1-Grocery-Data-Auths-Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#154]
PR: https://github.com/mcmillanator/6.1-6.4-grocery-data/pull/1
# TODO:
- [x] Create Sign Up functionality
- [x] Create Login / Logout functionality
- [x] Store a session id so user stays logged in until they log themselves out or close their browser
- [x] User must be able to view only their own items
