### ISSUE TITLE
6.1-4 - Grocery Data -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#156]
https://github.com/jasimper/6.1-4-GroceryData/pull/1
### Tasks
- [x] user authentication
- [x] the whole app must be on lock down (must be logged in to view the index page)
- [x] scoping the index page to _only_ show items _for the logged in user_
- [x] the index page is paginated on both the server & the client
  - [x] if JavaScript is turned off or doesn't load, then clicking "See more items" should still work
  - [x] if JavaScript is enabled & loaded, then it will asynchronously fetch and then load the fetched items on the page
