### ISSUE TITLE
6.3 - Jscript + Etsy -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#160]
**6.3: PR:** https://github.com/easmith2/6.3-jscript-etsy/pull/1
### Tasks
- [x] Clone the provided jscript files [here](https://github.com/TIY-Charleston-Front-End-May2015/assignments/tree/master/map-filter-fp)
- [x] Create repo and push original files
- [x] Answer all ze questions
- [x] Push the updated files and open a PR for review
