### ISSUE TITLE
6.4 - Grocery Data + Ajax -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#167]
**6.4: PR:** https://github.com/easmith2/6.1-6.4-Grocery-Data/pull/2
### Tasks
- [x] Update pagination
  - [x] Pagination implemented server-side only, functional when javascript disabled
  - [x] Ajax pagination implemented _ _sort of?_
- [ ] ~~Allow user to add items~~ _ _no way I am getting to this_
  - [ ] ~~Add view for available items~~
  - [ ] ~~Include crud actions for items~~
- [x] Test
  - [x] model tests written and green _ _sort of... need to review the tests again, since a lot of changes have been made_
  - [x] controller tests written and green _ _same comment as above_
- [ ] ~~Style~~ _ _or this_
- [x] Open a PR for review
