### ISSUE TITLE
6.3 - JS-Intro -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#168]
https://github.com/ryanmcgov/6.2-JS-Intro/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a project & initialize it with git
- [x] Commit the newly committed, unedited project to your `master` branch
- [x] Create a branch on called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Model all the things!
  - [x] Checkpoint: Created filters
  - [x] Complete: pushed all relevant code
