### ISSUE TITLE
6.4-grocery-data ajax pagination

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#171]
### Tasks
- [x] User authentication
- [x] The whole app must be on lock down (must be logged in to view the index page)
- [x] Scoping the index page to _only_ show items _for the logged in user_
- [ ] The index page is paginated on both the server & the client
  - [ ] If JavaScript is turned off or doesn't load, then clicking "See more items" should still work
  - [ ] If JavaScript is enabled & loaded, then it will asynchronously fetch and then load the fetched items on the page

**Comment by rpearce** [comment]
Mind linking me to a PR?

**Comment by rpearce** [comment]
@seanmpage did you ever have a PR for this?
