### ISSUE TITLE
7.1 -DTD - Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#172]
PR: https://github.com/mcmillanator/7.1-DTD/pull/1
![Do the Darth](http://stream1.gifsoup.com/view2/3403393/darth-vader-beat-it-o.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.1-To-Do`
- [x] Create a branch on `7.1-To-Do` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the To-Do list
  - [x] Checkpoint: Prevented the form's default page submission
  - [x] Checkpoint: Can add a new task
  - [x] HARD MODE: Can remove a task
  - [x] Complete: pushed all relevant code
