### ISSUE TITLE
7.1 - Darth Vader's ToDo List - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#173]
![](http://hopes-and-dreams.net/img/sw-dolist.gif)
## Solution

Link: https://github.com/andrewtpoe/7.1-todo_darth_vader/pull/1
## Requirements
- Make the form provided work (without using jQuery).
  - [x] Add the items on to the list using JavaScript
  - [x] When you hit enter the form will submit. Cancel this action
  - [x] When nothing is in the text box, cancel all actions or display error message
  - [x] HARD MODE - Make the remove item button work
