### ISSUE TITLE
7.1 - To-Do -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#174]
**PR:** https://github.com/easmith2/7.1-To-Do/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.1-To-Do`
- [x] Create a branch on `7.1-To-Do` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the To-Do list
  - [x] Checkpoint: Prevented the form's default page submission
  - [x] Checkpoint: Can add a new task
  - [ ] HARD MODE: Can remove a task
  - [ ] HARD MODE: Stylize
  - [ ] Complete: pushed all relevant code
