### ISSUE TITLE
7.1 todo - with Darth

### ISSUE THREAD

**Issue by Meeeeeesh** [tiy-chs-ruby/assignments-june-2015#175]
https://github.com/Meeeeeesh/todo-with-darth/pull/1
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.1-To-Do`
- [x] Create a branch on `7.1-To-Do` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the To-Do list
  - [x] Checkpoint: Prevented the form's default page submission
  - [x] Checkpoint: Can add a new task
  - [x] HARD MODE: Can remove a task
  - [x] Complete: pushed all relevant code
