### ISSUE TITLE
7.1 -  ToDo -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#178]
![](http://i.giphy.com/RvV4sUKIvrzGM.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.1-To-Do`
- [x] Create a branch on `7.1-To-Do` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the To-Do list
  - [x] Checkpoint: Prevented the form's default page submission
  - [x] Checkpoint: Can add a new task
  - [ ] HARD MODE: Can remove a task
  - [x] Complete: pushed all relevant code

[PR - 7.1](https://github.com/Kennethjk3/7.1-DarthVadars_ToDo/pull/1)
