### ISSUE TITLE
7.2-HexMex-seanpage

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#180]
https://github.com/seanmpage/7.2-HexMex/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.2-HexMex`
- [x] Create a branch on `7.2-HexMex` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the HexMex website
  - [x] Checkpoint: Linked HTML/CSS/JS files
  - [x] Checkpoint: Fetched JSON
  - [x] Checkpoint: Rendered palettes on the page
  - [x] Checkpoint: Styled palettes
  - [ ] Checkpoint: Refactored all code
  - [x] Complete: pushed all relevant code
