### ISSUE TITLE
7.2 - Hex Mex - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#183]
![](http://orig03.deviantart.net/2d6a/f/2011/227/a/8/color_magic_by_atillathehungarian-d46lswg.gif)
## Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called 7.2-HexMex
- [x] Create a branch on 7.2-HexMex called dev
- [x] In Github, open a PR from dev into master
- [x] Create the HexMex website
  - [x] Checkpoint: Linked HTML/CSS/JS files
  - [x] Checkpoint: Fetched JSON
  - [x] Checkpoint: Rendered palettes on the page
  - [x] Checkpoint: Styled palettes
  - [x] Checkpoint: Refactored all code
- [x] Complete: pushed all relevant code

I also styled the project using Sass. I wanted more experience using this tool.

**Comment by rpearce** [comment]
I think you forgot to drop a link to a PR here

**Comment by andrewtpoe** [comment]
@rpearce, My bad...

https://github.com/andrewtpoe/7.2_Hex_Mex/pull/1

**Comment by rpearce** [comment]
Very creative solution, and I believe we covered this in class the following day.
