### ISSUE TITLE
7.2-Hexmex-Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#184]
PR: https://github.com/mcmillanator/7.2-hexmex/compare/dev?expand=1

![Colors](http://orig00.deviantart.net/6877/f/2008/050/2/e/fractal_bubble_animated_by_kona_yuki.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.2-HexMex`
- [x] Create a branch on `7.2-HexMex` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the HexMex website
  - [x] Checkpoint: Linked HTML/CSS/JS files
  - [x] Checkpoint: Fetched JSON
  - [x] Checkpoint: Rendered palettes on the page
  - [x] Checkpoint: Styled palettes
  - [x] Checkpoint: Refactored all code
  - [x] Complete: pushed all relevant code
