### ISSUE TITLE
7.3 - Hex Mex Single Page App - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#188]
## Solution

Link: https://github.com/andrewtpoe/7.3-Hex-Mex-Single-Page-App/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `7.3 - pushState -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `7.3-pushState` containing at least a `README.md` file
- A Pull Request (PR) in your `7.3-pushState` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements
- after the data is fetched, it should be stored in `localStorage` or `sessionStorage`
  - all data should then be pulled from this storage in the future
- clicking on a palette title on the index/root path should navigate me (and the URL) to `/palettes/:id`
  - this `show` page should render all information pertaining to the palette
- there should be a link back to the root path
  - clicking this link should re-render the index
- clicking the browser's forwards & back buttons should work as expected
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.3-pushState`
- [x] Create a branch on `7.3-pushState` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the single-page app!
  - [x] Checkpoint: Stored all data in `localStorage` or `sessionStorage`
  - [x] Checkpoint: Added `history.pushState` call when links are clicked (the default action of a link is prevented & `pushState` is used to add history)
  - [x] Checkpoint: Able to view information successfully on show and index pages (and these sync with the URL)
  - [x] Checkpoint: Navigating to the index or the show page works by clicking links and forward/back browser buttons (except directly linking to the page... that is too much for this assignment)
  - [x] Complete: pushed all relevant code
