### ISSUE TITLE
1.3 - ATM - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#19]
Solution: https://github.com/andrewtpoe/1.3-Object-Oriented-ATM/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `1.3 - ATM -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `1.3-ATM` containing at least an `assignment.rb` file
- A Pull Request (PR) in your `1.3-ATM` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements

Running the program should
- prompt me for my name
  - If I enter nothing, then it should continue to prompt me for my name (bonus for a witty message)
- prompt me for what I would like to do
  - 1. Check my balance, 2. Withdraw Funds or 3. Cancel
  - if I enter a number that is not within this list, it needs to continue to prompt me to enter either 1, 2 or 3 (this should not be hardcoded--use `.count` and a Range to programmatically figure out what numbers are acceptable)
  - Check Balance
    - print to the console `"Your balance is __$$$__"`
  - Cancel
    - print to the console `"Thank you and please come again."`
  - Withdraw Funds
    - prompt for how much money to withdraw
      - if the amount is greater than the amount of money in the machine, print that the machine doesn't have that much money
      - if the amount is greater than the amount of money the user has available, print that the user has insufficient funds
      - if all is well, tell them to please take their money and then tell them their new balance
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.3-ATM`
- [x] Use the Github web interface to create a branch on `1.3-ATM` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Use [what we did in class](http://rpearce.gitbooks.io/ruby-june-2015/content/notes/1-2.html) as a reference
  - [x] prompt me for my name
    - [x] If I enter nothing, then it should continue to prompt me for my name (bonus for a witty message)
  - [x] prompt me for what I would like to do
    - [x] 1. Check my balance, 2. Withdraw Funds or 3. Cancel
    - [x] if I enter a number that is not within this list, it needs to continue to prompt me to enter either 1, 2 or 3 (this should not be hardcoded--use `.count` and a Range to programmatically figure out what numbers are acceptable)
    - [x] Check Balance
      - [x] print to the console `"Your balance is __$$$__"`
    - [x] Cancel
      - [x] print to the console `"Thank you and please come again."`
    - [x] Withdraw Funds
      - [x] prompt for how much money to withdraw
        - [x] if the amount is greater than the amount of money in the machine, print that the machine doesn't have that much money
        - [x] if the amount is greater than the amount of money the user has available, print that the user has insufficient funds
        - [x] if all is well, tell them to please take their money and then tell them their new balance
  - [x] Checkpoint: Used at least one method
  - [x] Checkpoint: Used at least one Range
  - [x] Checkpoint: Program can check more than 1 person's name & pin
  - [x] Complete: Pushed `assignment.rb`
