### ISSUE TITLE
7.3 - pushState - Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#190]
PR: https://github.com/mcmillanator/7.3-pushState/pull/1
![bwhahaha ](http://www.themarysue.com/wp-content/uploads/2013/10/56158-Doctor-Who-10-laughing-gif-d1CI.gif#geekosystem)
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.3-pushState`
- [x] Create a branch on `7.3-pushState` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the single-page app!
  - [x] Checkpoint: Stored all data in `localStorage` or `sessionStorage`
  - [x] Checkpoint: Added `history.pushState` call when links are clicked (the default action of a link is prevented & `pushState` is used to add history)
  - [x] Checkpoint: Able to view information successfully on show and index pages (and these sync with the URL)
  - [x] Checkpoint: Navigating to the index or the show page works by clicking links and forward/back browser buttons (except directly linking to the page... that is too much for this assignment)
  - [x] Complete: pushed all relevant code

**Comment by rpearce** [comment]
Is this when they're in the alternate universe and her dad is alive and having a party and the cybermen come!?
