### ISSUE TITLE
7.3 - pushState -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#191]
https://github.com/jasimper/7.3-pushState/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.3-pushState`
- [x] Create a branch on `7.3-pushState` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Create the single-page app!
  - [x] Checkpoint: Stored all data in `localStorage` or `sessionStorage`
  - [x] Checkpoint: Added `history.pushState` call when links are clicked (the default action of a link is prevented & `pushState` is used to add history)
  - [ ] Checkpoint: Able to view information successfully on show and index pages (and these sync with the URL)
  - [ ] Checkpoint: Navigating to the index or the show page works by clicking links and forward/back browser buttons (except directly linking to the page... that is too much for this assignment)
  - [ ] Complete: pushed all relevant code

**Comment by rpearce** [comment]
No worries on not finishing. It's hard...especially when you know there are tools that do this for you.
