### ISSUE TITLE
7.3 - pushState -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#192]
https://github.com/ryanmcgov/7.2-HexMex/pull/1 *
Continued using 7.2 HW
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.3-pushState`
- [x] Create a branch on `7.3-pushState` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the single-page app!
  - [x] Checkpoint: Stored all data in `localStorage` or `sessionStorage`
  - [ ] Checkpoint: Added `history.pushState` call when links are clicked (the default action of a link is prevented & `pushState` is used to add history)
  - [ ] Checkpoint: Able to view information successfully on show and index pages (and these sync with the URL)
  - [ ] Checkpoint: Navigating to the index or the show page works by clicking links and forward/back browser buttons (except directly linking to the page... that is too much for this assignment)
  - [ ] Complete: pushed all relevant code
