### ISSUE TITLE
7.3 - pushStates -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#195]
### Tasks
- [ ] Create a new Issue with these tasks!
- [ ] Create a repository called `7.3-pushState`
- [ ] Create a branch on `7.3-pushState` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] Create the single-page app!
  - [ ] Checkpoint: Stored all data in `localStorage` or `sessionStorage`
  - [ ] Checkpoint: Added `history.pushState` call when links are clicked (the default action of a link is prevented & `pushState` is used to add history)
  - [ ] Checkpoint: Able to view information successfully on show and index pages (and these sync with the URL)
  - [ ] Checkpoint: Navigating to the index or the show page works by clicking links and forward/back browser buttons (except directly linking to the page... that is too much for this assignment)
  - [ ] Complete: pushed all relevant code

[PR 7.3]()

**Comment by rpearce** [comment]
The PR link just links to this same page!

**Comment by Kennethjk3** [comment]
![](http://media.giphy.com/media/2IoGZIPp8IMLu/giphy.gif)

**Comment by Kennethjk3** [comment]
hah I'm redoing all the week 7 stuff cause i need more practice with JavaScript and React....I forgot I had this open.....
