### ISSUE TITLE
7.4 - React Hex Mex - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#197]
## Solution:

Link: https://github.com/andrewtpoe/7.4-React-Hex-Mex/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `7.4 - react-director -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `7.4-react-director` containing at least a `README.md` file
- A Pull Request (PR) in your `7.4-react-director` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.4-react-director`
- [x] Create a branch on `7.4-react-director` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the React app
  - [x] Checkpoint: Rendered a dummy React component to make sure it works
  - [x] Checkpoint: Boxed out the components' hierarchies
  - [x] Checkpoint: Fetched and rendered data via React
  - [x] Checkpoint: Initialized up router in main React component
  - [x] Checkpoint: Able to detect URL changes and re-render the app based on these changes
  - [x] HARD MODE Create a search box to sort palettes by title or category
  - [ ] HARD MODE Implement create and delete palette, have new colors rendered in index.
  - [x] Complete: pushed all relevant code
