### ISSUE TITLE
7.4-react-director-seanpage

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#198]
https://github.com/seanmpage/7.4-react-director/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.4-react-director`
- [x] Create a branch on `7.4-react-director` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the React app
  - [x] Checkpoint: Rendered a dummy React component to make sure it works
  - [x] Checkpoint: Boxed out the components' hierarchies
  - [x] Checkpoint: Fetched and rendered data via React
  - [x] Checkpoint: Initialized up router in main React component
  - [ ] Checkpoint: Able to detect URL changes and re-render the app based on these changes
  - [x] Complete: pushed all relevant code
