### ISSUE TITLE
7.4 - react-director -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#200]
**PR:** https://github.com/easmith2/7.4-React-Director/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `7.4-react-director`
- [x] Create a branch on `7.4-react-director` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Create the React app
  - [x] Checkpoint: Rendered a dummy React component to make sure it works
  - [x] Checkpoint: Boxed out the components' hierarchies
  - [x] Checkpoint: Fetched and rendered data via React
  - [x] Checkpoint: Initialized up router in main React component
  - [x] Checkpoint: Able to detect URL changes and re-render the app based on these changes
  - [ ] Hard mode: take advantage of local or session storage
  - [ ] Hard mode: allow filtering/sorting on index view
  - [x] Complete: pushed all relevant code
