### ISSUE TITLE
7.4 - React-Director -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#202]
![](https://sincyscience.files.wordpress.com/2013/02/funny-gif-nuclear-plant-drinking-tea.gif)
### Tasks
- [x] Create a new Issue with these tasks!
- [ ] Create a repository called `7.4-react-director`
- [ ] Create a branch on `7.4-react-director` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] Create the React app
  - [ ] Checkpoint: Rendered a dummy React component to make sure it works
  - [ ] Checkpoint: Boxed out the components' hierarchies
  - [ ] Checkpoint: Fetched and rendered data via React
  - [ ] Checkpoint: Initialized up router in main React component
  - [ ] Checkpoint: Able to detect URL changes and re-render the app based on these changes
  - [ ] Complete: pushed all relevant code

![7.4 - Pull Request]()
