### ISSUE TITLE
Collaborate -- APoe + ESmith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#204]
https://github.com/ALMakeABudget/MoneyMasters

https://www.pivotaltracker.com/projects/1402978
### Tasks | Day 1
- [x] Create a new Issue with these tasks!
- [x] Set up the organization & set up the app
  - [x] Checkpoint: Created organization & repository & forked it to your usernames
  - [x] Checkpoint: Set up the app
    - [x] Create new rails app with pg (default files)
    - [x] Add node packages (react, browserify pkgs), create own gitignore
    - [x] Need gemfile cleanup and browserify-rails, react added to gemfile
    - [x] Create home route & controller
    - [x] Render something using a react component
  - [x] Checkpoint: Successfully merged PRs to the upstream branch and fetched & rebased them back down to your fork's master branch from upstream
  - [x] Complete: pushed all relevant code
### Tasks | Days 2 & 3
- [x] Use [your issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `Collaboration -- YOUR TEAM NAME` with checkboxes for these tasks!
- [x] Use your GitHub organization & repo for you and your team & create this functionality
  - [x] Checkpoint: Created `Expense` data model & specs
  - [x] Checkpoint: Created `Expense` controller (`index` and `create` only) and specs
  - [x] Checkpoint: Can fetch from the index action via React and render the results
  - [x] Checkpoint: Can `POST` to the `Expense`'s `create` action and have this appear on the page when successful
  - [x] Complete: pushed all relevant code

**Comment by easmith2** [comment]
Question for @rpearce regarding these tasks:

>  Create a branch on Collaborate-8.1 called dev
>  In Github, open a PR from `dev` into `master`

We did not do this initially. (We merged our PRs into the master branch of the shared org's repo.) Is there a (simple) way to change this after the fact, or are we going to have to live without it?

**Comment by rpearce** [comment]
Heh. Missed that part

On Mon, Aug 3, 2015 at 8:04 PM, Elizabeth Smith notifications@github.com
wrote:

> Question for @rpearce https://github.com/rpearce regarding these tasks:
> 
> Create a branch on Collaborate-8.1 called dev
> In Github, open a PR from dev into master
> 
> We did not do this initially. (We merged our PRs into the master branch of
> the shared org's repo.) Is there a (simple) way to change this after the
> fact, or are we going to have to live without it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tiy-chs-ruby/assignments-june-2015/issues/204#issuecomment-127437464
> .

## 

Robert Pearce
http://www.robertwpearce.com
https://www.linkedin.com/in/robertwpearce
m-US: 1.843.568.9080
m-UK: +44 7477 424374

**Comment by rpearce** [comment]
Yeah so the assignment is wrong. Will fix
