### ISSUE TITLE
8 - Collaborate -- J Simper and K Kier

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#205]
https://github.com/GhostFaceBillaz/mo-money-mo-problems
### Tasks - Day 1
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Set up the organization & set up the app
  - [x] Checkpoint: Created organization & repository & forked it to your usernames
  - [x] Checkpoint: Set up the app
  - [x] Checkpoint: Successfully merged PRs to the upstream branch and fetched & rebased them back down to your fork's master branch from upstream
  - [x] Complete: pushed all relevant code
### Tasks - Day 2
- [x] Use [your issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `Collaboration -- YOUR TEAM NAME` with checkboxes for these tasks!
- [ ] Use your GitHub organization & repo for you and your team & create this functionality
  - [ ] Checkpoint: Created `Expense` data model & specs
  - [ ] Checkpoint: Created `Expense` controller (`index` and `create` only) and specs
  - [ ] Checkpoint: Can fetch from the index action via React and render the results
  - [ ] Checkpoint: Can `POST` to the `Expense`'s `create` action and have this appear on the page when successful
  - [ ] Complete: pushed all relevant code

**Comment by rpearce** [comment]
I do hope you get to come back to this! It's a great project to practice

**Comment by rpearce** [comment]
Sorry! I forgot you switched teams
