### ISSUE TITLE
8.1-collaborate-sean-meeeesh

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#206]
Everything works, except edit users, and the functionality of the "Budget" app is not really there. :) 
https://drizzle.herokuapp.com/

https://github.com/Makin-it-drizzle/8.1-fo-shizzle
https://www.pivotaltracker.com/n/projects/1403042
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a Rails project & initialize it with git
- [x] Commit the newly committed, unedited Rails project to your `master` branch
- [x] Create a branch on `Collaborate-8.1` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Set up the organization & set up the app
  - [x] Checkpoint: Created organization & repository & forked it to your usernames
  - [x] Checkpoint: Set up the app
  - [x] Checkpoint: Successfully merged PRs to the upstream branch and fetched & rebased them back down to your fork's master branch from upstream
  - [x] Complete: pushed all relevant code

**Comment by rpearce** [comment]
I get an internal server error when I try to sign up with an avatar :(

**Comment by rpearce** [comment]
Otherwise, very slick!
