### ISSUE TITLE
1.3 - ATM - Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#25]
**PR:** https://github.com/easmith2/1.3-atm/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.3-ATM`
- [x] Use the Github web interface to create a branch on `1.3-ATM` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Use [what we did in class](http://rpearce.gitbooks.io/ruby-june-2015/content/notes/1-2.html) as a reference
  - [x] Prompt for user's name
    - [x] If user enters nothing, then it should continue to prompt me for my name (bonus for a witty message)
  - [x] Prompt user for what they would like to do
    - [x] 1. Check Balance, 2. Withdraw Funds or 3. Cancel
    - [x] if a number entered is not within this list, it needs to continue to prompt to enter either 1, 2 or 3 (this should not be hardcoded--use `.count` and a Range to programmatically figure out what numbers are acceptable)
    - [x] Check Balance
      - [x] print to the console `"Your balance is __$$$__"`
    - [x] Cancel
      - [x] print to the console `"Thank you and please come again."`
    - [x] Withdraw Funds
      - [x] prompt for how much money to withdraw
        - [x] if the amount is greater than the amount of money in the machine, print that the machine doesn't have that much money
        - [x] if the amount is greater than the amount of money the user has available, print that the user has insufficient funds
        - [x] if all is well, tell them to please take their money and then tell them their new balance
  - [x] Checkpoint: Used at least one method
  - [x] Checkpoint: Used at least one Range
  - [x] Checkpoint: Program can check more than 1 person's name & pin
  - [x] Complete: Pushed `assignment.rb`
