### ISSUE TITLE
1.2 - Countries -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#26]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.2-Countries`
- [x] Use the Github web interface to create a branch on `1.2-Countries` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write a program that reads the countries file and returns the number of countries, as well as the syntactic updates mentioned above.
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Load in the `countries.txt` file
  - [x] Checkpoint: Programmatically determine how many countries there are
  - [x] Checkpoint: Capitalize each word in a country's name that is not `and`, `of` or `the`
  - [x] Checkpoint: Replace the `|` symbol with `-` (or " - ")
  - [x] Checkpoint: Write the newly formatted countries to a new file named `updated_countries.txt`
  - [x] Complete: Pushed `assignment.rb`

[Pull Request](https://github.com/Kennethjk3/1.2-Countries/pull/2)
[updated list PR](https://github.com/Kennethjk3/1.2-Countries/pull/4)
![](http://replygif.net/i/92.gif)

**Comment by rpearce** [comment]
@Kennethjk3 Have you gotten to this homework yet? If so, could you update the checklist here and link to where your code is?

If not, let's get together and talk through catching you up.

**Comment by rpearce** [comment]
Additionally, if it's a work in progress, add the `wip` label to it (on the right side) so that I know you are working on it.

**Comment by Kennethjk3** [comment]
hah yea I def could use some clearing up on some things.
I'm trying to do everything at once and i think i've confused myself.....

what time are you available to go through some things?

Ken K
Kennethjk3@gmail.com
Ken K Fixes http://www.facebook.com/FixitKenK

Additionally, if it's a work in progress, add the wip label to it (on the
right side) so that I know you are working on it.

**Comment by Kennethjk3** [comment]
Basically how my code has been acting all week....

![Story of my life!](https://buenosdinas.files.wordpress.com/2014/01/homer_cereal_fail.gif?w=480&h=360)

I have 3 or 4 more versions of this....
I seem to be having trouble tying everything back together.

**Comment by rpearce** [comment]
No problem. Recognition is Step 1. After lunch, let's sit upstairs and go through where you are and get you up to speed.

**Comment by rpearce** [comment]
I added 1 outstanding issue here:
https://github.com/Kennethjk3/1.2-Countries/issues/3

**Comment by rpearce** [comment]
Once you add that new file, I'll remove the `requires-revision` label and close this issue!
