### ISSUE TITLE
1.4 - ATM with Classes - Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#28]
**PR:** https://github.com/easmith2/1.4-ATM-Classes/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `1.4-ATM-Classes`
- [x] Create a branch on `1.4-ATM-Classes` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Use [what we did in class](http://rpearce.gitbooks.io/ruby-june-2015/content/notes/1-4.html) and [what we did at the end of yesterday](http://rpearce.gitbooks.io/ruby-june-2015/content/notes/1-3.html) as a reference
  - [x] Checkpoint: Parse the provided CSV in to `User` class instances
  - [x] Checkpoint: User Flow
    - [x] prompt me for my name
      - [x] If I enter nothing, then it should continue to prompt me for my name (bonus for a witty message)
    - [x] prompt me for what I would like to do
      - [x] 1. Check my balance, 2. Withdraw Funds or 3. Cancel
      - [x] if I enter a number that is not within this list, it needs to continue to prompt me to enter either 1, 2 or 3 (this should not be hardcoded--use `.count` and a Range to programmatically figure out what numbers are acceptable)
      - [x] Check Balance
        - [x] print to the console `"Your balance is __$$$__"`
      - [x] Cancel
        - [x] print to the console `"Thank you and please come again."`
      - [x] Withdraw Funds
        - [x] prompt for how much money to withdraw
          - [x] if the amount is greater than the amount of money in the machine, print that the machine doesn't have that much money
          - [x] if the amount is greater than the amount of money the user has available, print that the user has insufficient funds
          - [x] if all is well, tell them to please take their money and then tell them their new balance
    - [x] Complete: Pushed `assignment.rb`
    - [x] HARD MODE: Separate your class(es) in to different files of the same name as the class and require them in to your main `assignment.rb` file
    - [x] HARD MODE: Clear out the CSV at the end of the program and rewrite it with the new balance (make sure all the unchanged ones are still there)
