### ISSUE TITLE
1.1 - User Input - Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#3]
https://github.com/jasimper/1.1-user-input/pull/1
### Tasks
- [x] Create a new Issue with these tasks! (S)
- [x] Use the Github web interface to create a repository called `1.1-User-Input` (M)
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop` (M)
- [x] In Github, open a PR from `<initials>-develop` into `master` (S)
- [x] Create the Quick Star Wars Character test (M)
  - [x] Checkpoint: Create `assignment.rb` (S)
  - [x] Checkpoint: Store a person's name from a prompt (S)
  - [x] Checkpoint: Store a person's legal preference (S)
  - [x] Checkpoint: Perform logic on the legal preference (M)
  - [x] Checkpoint: Return one of the required strings back to the user. (M)
  - [x] Checkpoint: Commit `assignment.rb` (S)
  - [x] Complete: Pushed `assignment.rb`
