### ISSUE TITLE
2.1 - Data Modeling - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#37]
### Solution

Link: https://github.com/andrewtpoe/2.1-Data-Modeling/pull/1
### Requirements

There must be a `README.md` file that contains models as headings with their properties listed as bullet points underneath based on the following text:

> I have an idea for an app.
> 
> We are changing the way people manage their pictures! Someone should be able to sign in, upload a bunch of pictures and then be able to add information to each one like where it was taken, when it was taken and any additional notes. You know what? They should also be able to tag their family members. That sounds good.
> 
> Each member of our amazing service should be able to see all of their pictures, and so should their family. There should be some sort of grouping that groups people together and allows them to see and comment on all of their group's photos.
> 
> So how much will this cost me?

&mdash; Every picture startup founder ever.
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Data-Modeling`
- [x] Create a branch on `2.1-Data-Modeling` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write a Data Model
  - [x] Checkpoint: Create `README.md`
  - [x] Add either [markdown](https://help.github.com/articles/markdown-basics/) or an image of your data model (via `![](http://www.google.com/my_image.png)`) to `README.md`
  - [x] Complete: Pushed `README.md`
    - [ ] HARD MODE: Make this data model in to Ruby code
    - [ ] NIGHTMARE MODE: ...and make it work

**Comment by adam-kelsey** [comment]
This is looking very thorough, keep in mind the management of each "section" of the application. Editing of the user profile, deletion of pictures, editing of pictures data etc. Galleries could also be an added function to better organize the pictures. Just a few minor things to keep in mind, great work!
