### ISSUE TITLE
2.1 - Data Modeling -- Gregg Durishan

### ISSUE THREAD

**Issue by GreggDurishan** [tiy-chs-ruby/assignments-june-2015#39]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Data-Modeling`
- [x] Create a branch on `2.1-Data-Modeling` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `README.md`
  - [x] Add either [markdown](https://help.github.com/articles/markdown-basics/) or an image of your data model (via `![](http://www.google.com/my_image.png)`) to `README.md`
  - [x] Complete: Pushed `README.md`
    - [ ] HARD MODE: Make this data model in to Ruby code
    - [ ] NIGHTMARE MODE: ...and make it work

PR https://github.com/GreggDurishan/2.1-Data-Modeling/pull/1

**Comment by rpearce** [comment]
Just a note that metadata & comments & groups might potentially be data that is stored as one class/table like we touched on today
