### ISSUE TITLE
1.1 - User Input -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#4]
### Tasks
- [x] Create a new Issue with these tasks! (s)
- [x] Use the Github web interface to create a repository called `1.1-User-Input` (s)
- [x] Use the Github web interface to create a branch on `1.1-User-Input` called `<initials>-develop` (s)
- [x] In Github, open a PR from `<initials>-develop` into `master` (s)
- [x] Create the Quick Star Wars Character test (s)
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Store a person's name from a prompt
  - [x] Checkpoint: Store a person's legal preference
  - [x] Checkpoint: Perform logic on the legal preference
  - [x] Checkpoint: Return one of the required strings back to the user.
  - [x] Checkpoint: Commit `assignment.rb`
  - [x] Complete: Pushed `assignment.rb`
### If you're feeling brave...
- [x] Do not accept empty name
- [x] Do not accept empty pref
- [x] Do not accept a pref that is not 1-4 (buh-bye jar jar)

**PR:**  https://github.com/easmith2/1.1-user-input/pull/1
