### ISSUE TITLE
2.1 - Data Modeling - Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#41]
PR https://github.com/mcmillanator/2.1-Data-Modeling/pulls
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Data-Modeling`
- [x] Create a branch on `2.1-Data-Modeling` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `README.md`
  - [x] Add either [markdown](https://help.github.com/articles/markdown-basics/) or an image of your data model (via `![](http://www.google.com/my_image.png)`) to `README.md`
  - [ ] Complete: Pushed `README.md`
    - [ ] HARD MODE: Make this data model in to Ruby code
    - [ ] NIGHTMARE MODE: ...and make it work
