### ISSUE TITLE
2.1 - Data Modeling -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#42]
**PR:** https://github.com/easmith2/2.1-data-modeling/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Data-Modeling`
- [x] Create a branch on `2.1-Data-Modeling` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write a [something?]
  - [x] Checkpoint: Create `README.md`
  - [x] Add either [markdown](https://help.github.com/articles/markdown-basics/) or an image of your data model (via `![](http://www.google.com/my_image.png)`) to `README.md`
  - [x] Complete: Pushed `README.md`
    - [ ] HARD MODE: Make this data model in to Ruby code
    - [ ] NIGHTMARE MODE: ...and make it work

**Comment by adam-kelsey** [comment]
Looks great, very thorough!
