### ISSUE TITLE
2.1 - Data-Modeling -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#45]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Data-Modeling`
- [x] Create a branch on `2.1-Data-Modeling` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create `README.md`
  - [x] Add either [markdown](https://help.github.com/articles/markdown-basics/) or an image of your data model (via `![](http://www.google.com/my_image.png)`) to `README.md`
  - [ ] Complete: Pushed `README.md`
    - [ ] HARD MODE: Make this data model in to Ruby code
    - [ ] NIGHTMARE MODE: ...and make it work

[This is not my PR *wink *wink](https://github.com/Kennethjk3/2.1-Data-Modeling/pull/1)

![wootwoot](http://31.media.tumblr.com/beba6cc85910f36140b802d98bca9e0d/tumblr_nnzg4cu2Ew1un6da4o3_250.gif)

**Comment by adam-kelsey** [comment]
Looks good, keep in mind the editing/deleting of all sections. Also I like how you were thorough and added the friends part. I would also add first name and last name to the user section, so it can be pulled into photo labelling.

Props to the teen wolf gif!

**Comment by rpearce** [comment]
So confused by "this is not my PR"...
