### ISSUE TITLE
2.2 - Inheritance - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#47]
### Solution

![](http://media.giphy.com/media/10D4oCT4zUAvRK/giphy.gif)

Link: https://github.com/andrewtpoe/2.2-Super-Classes/tree/dev
### Requirements

You should utilize [inheritance](http://rubylearning.com/satishtalim/ruby_inheritance.html), methods, instances (with initialize), method overrides, getters/setters and any other skills to demonstrate that you understand class inheritance. Use dinosaur type classification (or another subject that interests you) to demonstrate this knowledge.
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.2-Inheritance`
- [x] Create a branch on `2.2-Inheritance` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write a program with the following:
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Sketch out similar (but different enough) classes and their attributes
  - [x] Checkpoint: Find shared attributes and pull them in to a `superclass` (aka "parent" class)
  - [x] Checkpoint: Inherit from this superclass
  - [x] Checkpoint: Create a superclass method that applies to all subclasses
  - [x] Checkpoint: Create a method in a child class that accepts an argument and is NOT a getter nor a setter created from `attr_accessor` that overrides its parent method of the same name and then calls `super` with the argument it requires
  - [x] Checkpoint: Given an instance of a subclass, `puts` out its class' `superclass`.
  - [x] Complete: Pushed `assignment.rb`

**Comment by adam-kelsey** [comment]
Code is looking good! Great gif by the way.

**Comment by andrewtpoe** [comment]
Thanks Adam!
