### ISSUE TITLE
2.2 - Inheritance -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#48]
https://github.com/ryanmcgov/2.2-Inheritance/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.1-Inheritance`
- [x] Create a branch on `2.1-Inheritance` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Write an Dino program
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Sketch out similar (but different enough) classes and their attributes
  - [x] Checkpoint: Find shared attributes and pull them in to a `superclass` (aka "parent" class)
  - [x] Checkpoint: Inherit from this superclass
  - [x] Checkpoint: Create a superclass method that applies to all subclasses
  - [ ] Checkpoint: Create a method in a child class that accepts an argument and is NOT a getter nor a setter created from `attr_accessor` that overrides its parent method of the same name and then calls `super` with the argument it requires
  - [ ] Checkpoint: Given an instance of a subclass, `puts` out its class' `superclass`.
  - [ ] Complete: Pushed `assignment.rb`

**Comment by rpearce** [comment]
Is this still a `wip`? If so, please take the time to finish this up. If not, please remove the `wip` label & mark off the checkboxes so that I know you're finished
