### ISSUE TITLE
2.3 - Testing -- Gregg Durishan

### ISSUE THREAD

**Issue by GreggDurishan** [tiy-chs-ruby/assignments-june-2015#53]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] Write an ATM program
  - [x] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [x] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [x] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [ ] Checkpoint: Write specs galore!
  - [x] Complete: Pushed `assignment.rb`

PR https://github.com/GreggDurishan/2.3-Testing/pull/1
