### ISSUE TITLE
2.3 - Testing - Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#55]
**PR:** https://github.com/easmith2/2.3_testing/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [x] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [x] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [x] Checkpoint: Write specs galore!
  - [x] Complete: Pushed `assignment.rb`
