### ISSUE TITLE
2.3 - Testing - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#56]
![](http://media.giphy.com/media/4hfpb3TSjQ6MU/giphy.gif)
### Solution

Link: https://github.com/andrewtpoe/2.3-Testing/tree/dev

May add more to tests.rb as necessity dictates, practice requires, or techniques improve.
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `2.3 - Testing -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `2.3-Testing` containing at least a `README.md` file
- A Pull Request (PR) in your `2.3-Testing` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements

Working in pairs, you should take ATM code from last week (either yours, your partner's or another student's) and add test coverage to every method/action that performs work and yields a result.

Use [this ATM code](https://github.com/andrewtpoe/1.4-ATM-Classes) if you want a place to get started.
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [x] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [x] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [x] Checkpoint: Write specs galore!
  - [x] Complete: Pushed `assignment.rb`

**Comment by adam-kelsey** [comment]
Looks very thorough, great job remembering to test for a negative amount withdrawal. That is an extremely important test for ATM's.
