### ISSUE TITLE
2.3 - Testing -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#58]
https://github.com/jasimper/2.3-Testing/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Write an ATM program
  - [x] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [x] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [x] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [x] Checkpoint: Write specs galore!
  - [x] Complete: Pushed `assignment.rb`

**Comment by rpearce** [comment]
Is this still a WIP?

**Comment by jasimper** [comment]
Yep. I've been avoiding it. Don't worry. I'll get to it ASAP.

**Comment by rpearce** [comment]
Thanks, Jamie. Rock on

On Wed, Jul 1, 2015 at 2:34 PM, Jamie Simper notifications@github.com
wrote:

> Yep. I've been avoiding it. Don't worry. I'll get to it ASAP.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tiy-chs-ruby/assignments-june-2015/issues/58#issuecomment-117790426
> .

## 

Robert Pearce
http://www.robertwpearce.com
https://www.linkedin.com/in/robertwpearce
m-US: 1.843.568.9080
m-UK: +44 7477 424374
