### ISSUE TITLE
1.1 - User Input - Michelle Hood

### ISSUE THREAD

**Issue by Meeeeeesh** [tiy-chs-ruby/assignments-june-2015#6]
### Tasks
- [x] Create a new Issue with these tasks! (S)
- [x] Use the Github web interface to create a repository called `1.1-User-Input`(FML)
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`(FFML)
- [ ] In Github, open a PR from `<initials>-develop` into `master`(WTFFML)
- [x] Create the Quick Star Wars Character test (S)
  - [x] Checkpoint: Create `assignment.rb`(S)
  - [x] Checkpoint: Store a person's name from a prompt (S)
  - [x] Checkpoint: Store a person's legal preference (S)
  - [x] Checkpoint: Perform logic on the legal preference (S)
  - [x] Checkpoint: Return one of the required strings back to the user. (S)
  - [x] Checkpoint: Commit `assignment.rb`(S)
  - [x] Complete: Pushed `assignment.rb`(S)

https://github.com/Meeeeeesh/1.1-User-Input

**Comment by rpearce** [comment]
@Meeeeeesh Could you provide a link to where your code is?

**Comment by rpearce** [comment]
You don't actually need `$stdin` on your `gets.chomp`. Apart from that and some spacing that is messed up, :+1:.

**Comment by rpearce** [comment]
Make sure you have a pull request from your `dev` branch to your `master` branch so I can comment on the code before you merge it!
