### ISSUE TITLE
2.4 - Zwitter -- Jamie Simper

### ISSUE THREAD

**Issue by jasimper** [tiy-chs-ruby/assignments-june-2015#60]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.4-Zwitter`
- [x] Create a branch on `2.4-Zwitter` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] Create & Test Zwitter
  - [x] Checkpoint: create (or use existing) working directory
  - [ ] Checkpoint: create `Program` class
  - [x] Checkpoint: create (or import) existing other classes from lecture (`Zombie`, `Tweet`)
  - [ ] Checkpoint: add all relevant attributes to classes
  - [ ] Checkpoint: create relationships between classes
  - [ ] Checkpoint: ability to create & destroy a `Tweet`, `Zombie`, & `Following`
  - [ ] Checkpoint: ability to create & destroy _through_ a relationship, e.g. `zombie.tweets.first.destroy`
  - [ ] Checkpoint: can access a zombie's tweet feed based on its following
  - [ ] Checkpoint: _think about this deeply and add your own checkpoints for what you think has been left out here._
  - [ ] Complete: pushed all relevant code
