### ISSUE TITLE
2.4-zwitter-sean page, stan

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#61]
https://github.com/mcmillanator/2.4-Zwitter/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.4-Zwitter`
- [x] Create a branch on `2.4-Zwitter` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create & Test Zwitter
  - [x] Checkpoint: create (or use existing) working directory
  - [x] Checkpoint: create `Program` class
  - [x] Checkpoint: create (or import) existing other classes from lecture (`Zombie`, `Tweet`)
  - [x] Checkpoint: add all relevant attributes to classes
  - [x] Checkpoint: create relationships between classes
  - [x] Checkpoint: ability to create & destroy a `Tweet`, `Zombie`, & `Following`
  - [x] Checkpoint: ability to create & destroy _through_ a relationship, e.g. `zombie.tweets.first.destroy`
  - [x] Checkpoint: can access a zombie's tweet feed based on its following
  - [x] Checkpoint: _think about this deeply and add your own checkpoints for what you think has been left out here._
  - [x] Complete: pushed all relevant code
