### ISSUE TITLE
2.4 - Zwitter -- E. Smith + J. Simper

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#62]
**PR:** https://github.com/easmith2/2.4_zwitter/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.4-Zwitter`
- [x] Create a branch on `2.4-Zwitter` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create & Test Zwitter
  - [x] Checkpoint: create (or use existing) working directory
  - [x] Checkpoint: create `Program` class
  - [x] Checkpoint: create (or import) existing other classes from lecture (`Zombie`, `Tweet`)
  - [x] Checkpoint: add all relevant attributes to classes
  - [x] Checkpoint: create relationships between classes
  - [x] Checkpoint: ability to create & destroy a `Tweet`, `Zombie`, & `Following`
  - [x] Checkpoint: ability to create & destroy _through_ a relationship, e.g. `zombie.tweets.first.destroy`
  - [x] Checkpoint: can access a zombie's tweet feed based on its following
  - [x] Checkpoint: create a subclass of tweet for a specific genre of tweet.
  - [x] Complete: pushed all relevant code
