### ISSUE TITLE
2.4 - Zwitter - Ken, Meesh, Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#63]
![](http://media.giphy.com/media/h4CLxot41RDdm/giphy.gif)
### Zwitter, a Terminal Twitter for Zombies!

Link: https://github.com/andrewtpoe/2.4-Zwitter/tree/dev
## Teammates:

Kenneth Kier 
Michelle Hood
Andrew T. Poe
## Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.4-Zwitter`
- [x] Create a branch on `2.4-Zwitter` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create & Test Zwitter
  - [x] Checkpoint: create (or use existing) working directory
  - [x] Checkpoint: create `Program` class
  - [x] Checkpoint: create (or import) existing other classes from lecture (`Zombie`, `Tweet`)
  - [x] Checkpoint: add all relevant attributes to classes
  - [x] Checkpoint: create relationships between classes
  - [x] Checkpoint: ability to create & destroy a `Tweet`, `Zombie`, & `Following`
  - [x] Checkpoint: ability to create & destroy _through_ a relationship, e.g. `zombie.tweets.first.destroy`
  - [x] Checkpoint: can access a zombie's tweet feed based on its following
  - [x] Checkpoint: Duplicate basic twitter functionality in the 'terminal' for all the zombies in the world.
  - [x] Complete: pushed all relevant code

**Comment by rpearce** [comment]
Mind making this a Pull Request to your `master` branch so that I can comment on all the things?

**Comment by andrewtpoe** [comment]
My bad.

Pull Request: https://github.com/andrewtpoe/2.4-Zwitter/pull/5
