### ISSUE TITLE
1.1 - User Input -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#7]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.1-User-Input`
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [x] In Github, open a PR from `<initials>-develop` into `master`
- [x] Create the Quick Star Wars Character test
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Store a person's name from a prompt
  - [x] Checkpoint: Store a person's legal preference
  - [x] Checkpoint: Perform logic on the legal preference
  - [x] Checkpoint: Return one of the required strings back to the user.
  - [x] Checkpoint: Commit `assignment.rb`
  - [x] Complete: Pushed `assignment.rb`

**Comment by Kennethjk3** [comment]
Was the Assignment supposed to be added as part of the branch? I added it to the  <initials>-develop file and PRed it.

**Comment by rpearce** [comment]
Just add the link the PR in your repository in the comments here so I can find it! In the other PR, you can include notes about your code, if you like, though I do demand a cute/funny/relevant gif, added like this

```
This is my PR!
![](http://www.google.com/image.gif)
```

**Comment by Kennethjk3** [comment]
This is my PR: 
https://github.com/Kennethjk3/1.1-User-Input/pull/1

gif tax:

![Confirmed...](http://i.imgur.com/Kq77TZe.jpg)
