### ISSUE TITLE
2.3 - Testing - Stan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#72]
PR: https://github.com/mcmillanator/2.3-Minitest/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Test an ATM program
  - [x] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [x] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [x] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [x] Checkpoint: Write specs galore!
  - [x] Complete: Pushed `assignment.rb`

:(  I forgot to create this issue last week.  Sorry!

**Comment by rpearce** [comment]
Thank you.
