### ISSUE TITLE
3.1-First-Website - Gregg Durishan

### ISSUE THREAD

**Issue by GreggDurishan** [tiy-chs-ruby/assignments-june-2015#73]
PR https://github.com/GreggDurishan/3.1-First-Website/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.1-First-Website`
- [x] Create a branch on `3.1-First-Website` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Port the images
  - [x] Checkpoint: `index.html` file created
  - [x] Checkpoint: `styles.css` file created
  - [ ] Checkpoint: acquire relevant images & place within `images/` folder
  - [x] Checkpoint: create markup based on conceptual drawing(s)
  - [x] Checkpoint: add styles for context & design
  - [ ] Checkpoint: slap self on back for excellence
  - [x] Checkpoint: remove instructor's guide comments
  - [x] Complete: pushed all relevant code
