### ISSUE TITLE
3.2 - Responsivize -- Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#77]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.2-Responsivize`
- [x] Create a branch on `3.2-Responsivize` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Adjust the website
  - [ ] Checkpoint: Added full-height/width background image at any resolution to header/title section
  - [x] Checkpoint: top sections of each half (only when halved) line up accordingly
  - [ ] Checkpoint: 2 images added throughout the content
  - [x] Checkpoint: used responsive web design to redefine page elements when the page is `600px` wide or below
  - [ ] Checkpoint: validated the page doesn't look like crap
  - [ ] Complete: pushed all relevant code

[PR](https://github.com/Kennethjk3/3.2-Responsivize/pull/1)

![](http://i952.photobucket.com/albums/ae7/ddlmarriot/Stuff/Shark_eats_plane.gif~original)
yea, found it
