### ISSUE TITLE
3.2 - Responsivize -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#78]
https://github.com/ryanmcgov/3.2-Responsivize/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.2-Responsivize`
- [x] Create a branch on `3.2-Responsivize` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Adjust the website
  - [x] Checkpoint: Added full-height/width background image at any resolution to header/title section
  - [x] Checkpoint: top sections of each half (only when halved) line up accordingly
  - [ ] Checkpoint: 2 images added throughout the content
  - [x] Checkpoint: used responsive web design to redefine page elements when the page is `600px` wide or below
  - [x] Checkpoint: validated the page doesn't look like crap
  - [x] Complete: pushed all relevant code
