### ISSUE TITLE
1.1 - User Input -- Robert Pearce (TEST)

### ISSUE THREAD

**Issue by rpearce** [tiy-chs-ruby/assignments-june-2015#8]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.1-User-Input`
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [x] In Github, open a PR from `<initials>-develop` into `master`
- [x] Create the Quick Star Wars Character test
  - [ ] Checkpoint: Create `assignment.rb`
  - [ ] Checkpoint: Store a person's name from a prompt
  - [ ] Checkpoint: Store a person's legal preference
  - [ ] Checkpoint: Perform logic on the legal preference
  - [ ] Checkpoint: Return one of the required strings back to the user.
  - [ ] Checkpoint: Commit `assignment.rb`
  - [ ] Complete: Pushed `assignment.rb`

PR:
https://github.com/rpearce/1.1-user-input/pull/1

**Comment by rpearce** [comment]
Hey, berto, what is wrong with this code?

``` ruby
puts hello, world
```
