### ISSUE TITLE
3.3 - SASS -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#82]
https://github.com/ryanmcgov/3.3---SASS/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.3-Sass`
- [x] Create a branch on `3.3-Sass` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the website
  - [x] Checkpoint: Created folder called `sass`
  - [x] Checkpoint: Created main file
  - [x] Checkpoint: Abstracted relevant code to separate files
  - [x] Checkpoint: Imported separated code from partials in to main file
  - [x] Checkpoint: Used a variable
  - [x] Checkpoint: Used a mixin
  - [x] Checkpoint: Used nesting
  - [x] Checkpoint: Used nesting
  - [ ] HARD MODE: Used a list
  - [ ] HARD MODE: Used an `@each` loop
  - [ ] HARD MODE: Created classes dynamically from a list and a loop
  - [x] Complete: pushed all relevant code
