### ISSUE TITLE
3.3 -- Sass -- Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#84]
![](http://media.giphy.com/media/kWWLdVaayztrW/giphy.gif)
### Solution

Link: https://github.com/andrewtpoe/3.3-Sass/tree/dev
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `3.3 - Sass -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `3.3-Sass` containing at least a `README.md` file
- A Pull Request (PR) in your `3.3-Sass` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements

Using your homework assignment from yesterday, refactor your CSS to Sass and add more functionality if necessary. Your homework should include, but not be limited to utilizing
- mixins
- variables
- partials/importing
- nesting

The aforementioned are what we covered in class. Please also find a way to include
- a list
- iterating over a list with `@each`
- creating classes dynamically via interpolation within the `@each` block
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.3-Sass`
- [x] Create a branch on `3.3-Sass` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the website
  - [x] Checkpoint: Created folder called `sass`
  - [x] Checkpoint: Created main file
  - [x] Checkpoint: Abstracted relevant code to separate files
  - [x] Checkpoint: Imported separated code from partials in to main file
  - [x] Checkpoint: Used a variable
  - [x] Checkpoint: Used a mixin
  - [x] Checkpoint: Used nesting
  - [ ] HARD MODE: Used a list
  - [ ] HARD MODE: Used an `@each` loop
  - [ ] HARD MODE: Created classes dynamically from a list and a loop
  - [x] Complete: pushed all relevant code
