### ISSUE TITLE
3.3 - Sass -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#87]
**PR:** https://github.com/easmith2/3.3-Sass/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.3-Sass`
- [x] Create a branch on `3.3-Sass` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the website
  - [x] Checkpoint: Created folder called `sass`
  - [x] Checkpoint: Created main file
  - [x] Checkpoint: Abstracted relevant code to separate files
  - [x] Checkpoint: Imported separated code from partials in to main file
  - [x] Checkpoint: Used a variable
  - [x] Checkpoint: Used a mixin
  - [x] Checkpoint: Used nesting
  - [ ] HARD MODE: Used a list
  - [ ] HARD MODE: Used an `@each` loop
  - [ ] HARD MODE: Created classes dynamically from a list and a loop
  - [x] Complete: pushed all relevant code

**Comment by easmith2** [comment]
I didn't include a sass list or `@each` loop, mostly because I couldn't think of a place where that would be useful. The syntax of lists/loops looks fairly straightforward, and I'd like to try it, so if you see a place where it would make sense, just point it out and I'll give it a shot.

**Comment by rpearce** [comment]
@easmith2 I didn't really see one here, but for hard mode it would have probably required adding some more functionality
