### ISSUE TITLE
3.4 - Surf And Paddle -- Ryan

### ISSUE THREAD

**Issue by ryanmcgov** [tiy-chs-ruby/assignments-june-2015#88]
https://github.com/ryanmcgov/3.4-Surf-And-Paddle/pull/1
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `3.3-Surf-And-Paddle`
- [x] Create a branch on `3.3-Surf-And-Paddle` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the website
  - [x] Checkpoint: Created folder called `sass`
  - [x] Checkpoint: Created main file
  - [x] Checkpoint: Abstracted relevant code to separate files
  - [x] Checkpoint: Imported separated code from partials in to main file
  - [x] Checkpoint: Create Mobile First Design
  - [ ] Checkpoint: Add support for larger formats
  - [ ] Complete: pushed all relevant code

Mobile design is based off of ResponsiveDesignV1-Mobile.psd.  I didn't see the other one.

**Comment by rpearce** [comment]
Having a check list here is good for letting me know your progress.

**Comment by ryanmcgov** [comment]
Just put one up.  Made this on Thursday and it slipped my mind to add a checklist.

**Comment by ryanmcgov** [comment]
Still working on transitioning to the larger view.  I know what I need to do, but I'd like to look at it with fresh eyes tomorrow.
