### ISSUE TITLE
3.4 - Surf and Paddle -- Elizabeth Smith

### ISSUE THREAD

**Issue by easmith2** [tiy-chs-ruby/assignments-june-2015#89]
**PR:** https://github.com/easmith2/3.4-Surf-Paddle/pull/1
## Normal Mode

Using the image `assets/surf-and-paddle.png` located [here](https://github.com/theironyard/rb-assignments/tree/master/projects/surfandpaddle), create an html document using html and css to look like the image and function as a responsive website. (See [image here](https://raw.githubusercontent.com/theironyard/rb-assignments/master/projects/surfandpaddle/assets/surf-and-paddle.png).)
### Tasks
- [x] Checkpoint: Created `index.html` and outline general page layout
- [x] Collect required images
  - [x] header, post, author, and ad
  - [x] icons
- [x] Checkpoint: Add styles for general layout and formatting
  - [x] create a generic transparent overlay
  - [x] figure out removal of overlay on hover
- [x] Checkpoint: Add breakpoints and adjust styles for each
- [x] Complete: pushed all relevant code
