### ISSUE TITLE
1.1 - User Input -- Sean Page

### ISSUE THREAD

**Issue by seanmpage** [tiy-chs-ruby/assignments-june-2015#9]
### Tasks
- [x] Create a new Issue with these tasks! 
- [x] Use the Github web interface to create a repository called `1.1-User-Input`
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [x] In Github, open a PR from `<initials>-develop` into `master`
- [x] Create the Quick Star Wars Character test
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Store a person's name from a prompt
  - [x] Checkpoint: Store a person's legal preference
  - [x] Checkpoint: Perform logic on the legal preference
  - [x] Checkpoint: Return one of the required strings back to the user.
  - [x] Checkpoint: Commit `assignment.rb`
  - [x] Complete: Pushed `assignment.rb`

https://github.com/seanmpage/1.1-user-input/pull/1

_Notes_:
- blah blah.
