### ISSUE TITLE
2.2-Inheritance--Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#94]
### Tasks
- [ ] Create a new Issue with these tasks!
- [ ] Create a repository called `2.2-Inheritance`
- [ ] Create a branch on `2.2-Inheritance` called `dev`
- [ ] In Github, open a PR from `dev` into `master`
- [ ] Write an ATM program
  - [ ] Checkpoint: Create `assignment.rb`
  - [ ] Checkpoint: Sketch out similar (but different enough) classes and their attributes
  - [ ] Checkpoint: Find shared attributes and pull them in to a `superclass` (aka "parent" class)
  - [ ] Checkpoint: Inherit from this superclass
  - [ ] Checkpoint: Create a superclass method that applies to all subclasses
  - [ ] Checkpoint: Create a method in a child class that accepts an argument and is NOT a getter nor a setter created from `attr_accessor` that overrides its parent method of the same name and then calls `super` with the argument it requires
  - [ ] Checkpoint: Given an instance of a subclass, `puts` out its class' `superclass`.
  - [ ] Complete: Pushed `assignment.rb`

[Link toPR](https://github.com/Kennethjk3/2.2-Inheritance/pull/1)
used Mr.Poe's for guidance cause I can understand it.....still reworking it.

in the mean time...think about this! 
![](http://24.media.tumblr.com/tumblr_lx0a6tzhSt1r0f8s0o1_500.gif)

**Comment by Kennethjk3** [comment]
Changed the link to go to PR

Question: in the class Charmander..... 
1. Is this a necessary class if I have:       charmander = Charmander.new?
would I just need to do:     charmander = Fire_type(charmander)
1. how would I interpolate the instance name in I Choose You?
   doing charmander.name puts the instance of charmander instead of the :name
