### ISSUE TITLE
2.3-Testing--Kenneth Kier

### ISSUE THREAD

**Issue by Kennethjk3** [tiy-chs-ruby/assignments-june-2015#95]
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `2.3-Testing`
- [x] Create a branch on `2.3-Testing` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [ ] Test an ATM program
  - [ ] Checkpoint: Create a `tests.rb` file (or one for each class...)
  - [ ] Checkpoint: Set up the file to run MiniTest specs from the command line
  - [ ] Checkpoint: `require` your ATM application and/or any other files you might want to test. You can do this in 1 file or multiple test files (and you can even have 1 test file that `require`s all the others and you just run that one!)
  - [ ] Checkpoint: Write specs galore!
  - [ ] Complete: Pushed `assignment.rb`

[Link to PR](https://github.com/Kennethjk3/2.3-Minitest_ATM/pull/1)
![](http://awesomegifs.com/wp-content/uploads/nintendos-world.gif)

**Comment by rpearce** [comment]
Is this a `wip`? If not, please check off these checkboxes for ones you have completed and create a Pull Request (as explained in these checkboxes above)

**Comment by Kennethjk3** [comment]
wip'd it and linked to the PR
