### ISSUE TITLE
4.1 - Sinatra - Andrew T. Poe

### ISSUE THREAD

**Issue by andrewtpoe** [tiy-chs-ruby/assignments-june-2015#99]
![](http://media.giphy.com/media/3eE7PuC4qxxVm/giphy.gif)
### Solution

Link: https://github.com/andrewtpoe/4.1-Sinatra/pull/1
### Deliverables
- [An issue in the class repo](https://github.com/tiy-chs-ruby/assignments-june-2015) titled `4.1 - Sinatra -- YOUR NAME` with checkboxes as below under _Requirements_.
- A repository named `4.1-Sinatra` containing at least a `README.md` file
- A Pull Request (PR) in your `4.1-Sinatra` repo:
  - _from_ branch `dev`
  - _into_ branch master
- A comment on your original Issue with a link to your PR
### Requirements

Take your weekend lab assignment, Surf & Paddle, and convert it to a server-rendered Sinatra application. This assignment should include
- an `app.rb` file that routes to at least `'/'`, `'/my-post'`, and `'/my-other-post'`
- a layout file
- a separate, new index page that links to at least 2 different surf & paddle blog posts
- partial rendering
- passing a local variable to a template/partial
- HARD MODE: use the same template/partial for both blog posts
### Tasks
- [x] Create a new Issue with these tasks!
- [x] Create a repository called `4.1-Sinatra`
- [x] Create a branch on `4.1-Sinatra` called `dev`
- [x] In Github, open a PR from `dev` into `master`
- [x] Create the Sinatra App
  - [x] Checkpoint: Create a `Gemfile`, `app.rb`, and your `views/` directory
  - [x] Checkpoint: Set the Gemfile to install `sinatra`
  - [x] Checkpoint: Set up your `app.rb` to route to at least `'/'`, `'/my-post'`, and `'/my-other-post'`
  - [x] Checkpoint: Create a layout file
  - [x] Checkpoint: Create a separate, new index page (located at `'/'`) that links to at least 2 different surf & paddle pages
  - [x] Checkpoint: Create an index file and a post file(s) and any other necessary partials
  - [x] Checkpoint: Make sure each page has the appropriate `<title>`
  - [ ] Checkpoint: HARD MODE: Use the same template/partial for both blog posts
  - [x] Complete: pushed all relevant code
